name: "GitHub Action Locks"
author: "@abatilo"
description: "An action to lock the concurrent executions of your Actions"
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "lock.sh"
  post-entrypoint: "unlock.sh"
branding:
  icon: "lock"
  color: "gray-dark"
