name: "GitHub Action Locks"
author: "@abatilo"
description: "An action to lock the concurrent executions of your Actions"
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/lock.sh"
  post-entrypoint: "/unlock.sh"
branding:
  icon: "lock"
  color: "gray-dark"
inputs:
  timeout:
    description: "How long to wait to acquire a lock, in minutes"
    required: false
    default: "30"
  table:
    description: "DynamoDB table to write the lock in"
    required: false
    default: "github-action-locks"
  key:
    description: "Name of the column where we write locks"
    required: false
    default: "LockID"
  name:
    description: "Name of the lock"
    required: false
    default: "foobar"
