name: "GitHub Action Locks"
author: "@abatilo"
description: "An action to lock the concurrent executions of your Actions"
runs:
  using: "docker"
  image: "Dockerfile"
  entrypoint: "/lock.sh"
  post-entrypoint: "/unlock.sh"
branding:
  icon: "lock"
  color: "gray-dark"
inputs:
  timeout:
    description: "How long to wait before giving up on acquiring the lock, in minutes"
    required: false
    default: "30"
  table:
    description: "The DynamoDB table to create the lock in"
    required: false
    default: "github-action-locks"
  key:
    description: "The name of the column in the DynamoDB table to use for storing the lock name"
    required: false
    default: "LockID"
  name:
    description: "The name of lock to hold"
    required: false
    default: "testing"
